meta_product_name: "Heal line"
meta_title: "Heal line - Suivez votre parcours de santé"
meta_description: "Suivez votre parcours de santé"
meta_image: "logo-1200x630.png" # should exist in `app/assets/images/`